import type { FinanceState } from './entities/finance';

const today = new Date();
const isoDaysAgo = (days: number) =>
  new Date(today.getFullYear(), today.getMonth(), today.getDate() - days).toISOString();
const futureMonth = (months: number) =>
  new Date(today.getFullYear(), today.getMonth() + months, 1).toISOString();

export const seedFinanceState: FinanceState = {
  profile: {
    name: 'Shraj',
    monthlySalary: 86000,
    expectedSalaryMin: 110000,
    expectedSalaryMax: 120000,
    salaryDay: 1,
    currencyCode: 'INR',
    currencySymbol: 'Rs',
    creditCardLimit: 20800,
    monthlySavingsTarget: 18000,
    fixedExpenses: [
      {
        id: 'parents-support',
        name: 'Parents Support',
        amount: 28000,
        category: 'Parents',
        dueDay: 1,
        paidThisMonth: true,
      },
      {
        id: 'rent',
        name: 'Rent',
        amount: 10500,
        category: 'Rent',
        dueDay: 5,
        paidThisMonth: true,
      },
      {
        id: 'brother-emi',
        name: 'Brother Credit Card EMI',
        amount: 5000,
        category: 'EMI',
        dueDay: 10,
        paidThisMonth: true,
      },
      {
        id: 'utilities',
        name: 'Utilities',
        amount: 3000,
        category: 'Utilities',
        dueDay: 15,
        paidThisMonth: false,
      },
    ],
  },
  transactions: [
    {
      id: 'seed-groceries',
      title: 'Monthly groceries',
      amount: 4200,
      category: 'Groceries',
      date: isoDaysAgo(2),
      paymentMode: 'UPI',
      type: 'expense',
      notes: 'Staples and household essentials',
      tags: ['home'],
      recurring: false,
    },
    {
      id: 'seed-pet',
      title: 'Pet food and care',
      amount: 3300,
      category: 'Pet',
      date: isoDaysAgo(4),
      paymentMode: 'Credit Card',
      type: 'expense',
      notes: '',
      tags: ['pet'],
      recurring: false,
    },
    {
      id: 'seed-travel',
      title: 'Office travel',
      amount: 2600,
      category: 'Travel',
      date: isoDaysAgo(6),
      paymentMode: 'UPI',
      type: 'expense',
      notes: '',
      tags: ['commute'],
      recurring: false,
    },
    {
      id: 'seed-food',
      title: 'Dinner with team',
      amount: 1450,
      category: 'Food',
      date: isoDaysAgo(8),
      paymentMode: 'Credit Card',
      type: 'expense',
      notes: '',
      tags: ['social'],
      recurring: false,
    },
  ],
  goals: [
    {
      id: 'emergency-fund',
      name: 'Emergency Fund',
      targetAmount: 150000,
      currentSavings: 32000,
      monthlyContribution: 8000,
      deadline: futureMonth(8),
      note: 'Three months of core expenses.',
    },
    {
      id: 'gaming-laptop',
      name: 'Gaming Laptop',
      targetAmount: 95000,
      currentSavings: 18000,
      monthlyContribution: 5000,
      deadline: futureMonth(6),
      note: 'Buy only if cash flow stays disciplined.',
    },
    {
      id: 'singapore-trip',
      name: 'Singapore Trip',
      targetAmount: 120000,
      currentSavings: 7000,
      monthlyContribution: 3000,
      deadline: futureMonth(12),
      note: 'Travel fund after emergency buffer improves.',
    },
  ],
  creditCards: [
    {
      id: 'primary-card',
      cardName: 'Primary Credit Card',
      limit: 20800,
      currentUsage: 4750,
      statementDay: 18,
      dueDay: 5,
      minimumDue: 500,
      outstanding: 4750,
    },
  ],
};
